#######################################################################################
# Book settings
title: Python Climate Visuals
author: Xiaogang HE
email: 'hexg@nus.edu.sg'
logo                        : "favicon.png"  # A path to the book logo
exclude_patterns            : ["README.md"]  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : 'off'  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout                   : 600    # The maximum time (in seconds) each notebook cell is allowed to run.

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "favicon.png"  # A path to a favicon image
  navbar_number_sections    : True  # Add a number to each section in your left navbar
  google_analytics_id       : "UA-148221575-1"  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://xiaoganghe.github.io/python-climate-visuals/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  use_repository_button     : true
  use_edit_page_button      : false
  use_issues_button         : false
  use_multitoc_numbering    : false

#######################################################################################
# Launch button settings
launch_buttons:
  jupyterhub_url            : https://datahub.berkeley.edu
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)

repository:
  url                       : https://github.com/XiaogangHe/python-climate-visuals  # The URL to your book's repository
  branch                    : main  # Which branch of the repository should be used when creating links

sphinx:
  config:
    html_extra_path: ['assets']
